# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
name: $(common-razor)$(rev:.r)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/Common.Razor/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:  
- group: versions
- name: buildPlatform
  value: 'Any CPU'
- name: BuildConfiguration
  value: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Common.Razor/Common.Razor.csproj'
    arguments: '/p:Configuration=$(BuildConfiguration) /p:PackageVersion=$(Build.BuildNumber)'

- task: CopyFiles@2
  inputs:
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

